# Generated by Django 4.2 on 2024-04-04 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_category', models.CharField(choices=[('Financial income', 'Financial income'), ('Income', 'Income'), ('Other', 'Other')], max_length=50)),
                ('income_amount', models.IntegerField(default=0)),
                ('income_payment_method', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=50)),
                ('income_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('income_comment', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', models.CharField(choices=[('Food/Drinks', 'Food/Drinks'), ('Clothing', 'Clothing'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Home', 'Home'), ('Family', 'Family'), ('Sport/Health', 'Sport/Health'), ('Pets', 'Pets'), ('Subscriptions', 'Subscriptions'), ('Bills/Utiliets', 'Bills and Utilietes'), ('Education', 'Education'), ('Groceries', 'Groceries')], max_length=50)),
                ('expense_amount', models.IntegerField(default=0)),
                ('expense_payment_method', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], max_length=50)),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense_comment', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
