# Generated by Django 4.2 on 2024-03-24 08:47

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_category', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Financial income', 'Financial income'), ('Income', 'Income'), ('Other', 'Other')], enum_class=app.models.IncomeCategory, max_length=16)),
                ('income_amount', models.IntegerField(default=0)),
                ('income_payment_method', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Wallet', 'Wallet'), ('Card', 'Card')], enum_class=app.models.PaymentMethod, max_length=6)),
                ('income_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('income_comment', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_category', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Enterteinment', 'Enterteinment'), ('Food', 'Food'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Family', 'Family'), ('Other', 'Other')], enum_class=app.models.ExpenseCategory, max_length=13)),
                ('expense_amount', models.IntegerField(default=0)),
                ('expense_payment_method', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Wallet', 'Wallet'), ('Card', 'Card')], enum_class=app.models.PaymentMethod, max_length=6)),
                ('expense_date', models.DateTimeField()),
                ('expense_comment', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
