# Generated by Django 4.2 on 2024-04-13 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_expense_expense_date_alter_income_income_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
